language: php

matrix:
    include:
        - name: 7.1 (tests)
          php: '7.1'
          env:
              - INSTALL_COMMAND="composer install"
              - MAIN_COMMAND="composer tests"

        - name: 7.2 (all)
          php: '7.2'
          env:
              - INSTALL_COMMAND="composer install"
              - MAIN_COMMAND="composer all"

        - name: 7.2 (tests, lowest deps)
          php: '7.2'
          env:
              - INSTALL_COMMAND="composer update --prefer-lowest --prefer-stable"
              - MAIN_COMMAND="composer tests"

        - name: nightly (tests)
          php: nightly
          env:
              - INSTALL_COMMAND="composer install"
              - MAIN_COMMAND="composer tests"

install: ${INSTALL_COMMAND}

script: ${MAIN_COMMAND}
